name = "HydroTools"
uuid = "179359cd-bac3-4aa1-bccd-287172463ab0"
authors = ["Dongdong Kong <kongdd@users.noreply.github.com>"]
version = "0.1.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FieldMetadata = "bf96fef3-21d2-5d20-8afa-0e7d4c32a885"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"

[compat]
DataFrames = "1.6"
DataStructures = "0.18, 0.19"
DocStringExtensions = "0.9"
FieldMetadata = "0.3"
Parameters = "0.12"
Reexport = "1"
Statistics = "1.9, 1.10"
UnPack = "1.0"
julia = "1.9, 1.10"
